spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: rest_api
    password: rest_api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
# DEIXAR COMENTADO, POIS EXISTE UM BUG AINDA N√ÉO REOVIDO. COMENTANDO AQUI RODA NORMALMENTE
#   properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle11gDialect 
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'